SPOOL ACCOUNT_BRT.LOG

SET SERVEROUTPUT ON;
SET TIME ON;
SET TIMING ON;

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;

EXEC DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'DD-MM-YYYY HH24:MI:SS')||'- INICIO');

INSERT /*+ APPEND */INTO APP_RELOWN.ACCOUNT
	SELECT /*+ PARALLEL(STG,20) */
	        'B' AS PARTITION_KEY,
		APP_RELOWN.SEQ_SRK_ACCOUNT.NEXTVAL,
		stg.CLI_COD,											-- 5 CODACTCRM
		CASE 
					WHEN stg.CLI_TIPOPESSOA=1 THEN 'C'
					WHEN stg.CLI_TIPOPESSOA=2 THEN 'B'
					ELSE NULL
		END,													-- 6 BUSTYP
		TO_DATE(stg.CLI_DATCADALT,'YYYYMMDDHH24MISS'),			-- 7 DTEUPDACT
		TO_DATE(stg.CLI_DATACAD,'YYYYMMDDHH24MISS'),			-- 8 DTECREACT
		stg.CLI_LOGIN,											-- 9 EMAACT
		CASE
			WHEN STG.CLI_TIPOPESSOA = 2 THEN SUBSTR(TRIM(STG.CLI_CONTATO), 1, DECODE(INSTR(TRIM(STG.CLI_CONTATO), ' '), 0, LENGTH(TRIM(STG.CLI_CONTATO)), INSTR(TRIM(STG.CLI_CONTATO), ' ')))
			ELSE                             SUBSTR(TRIM(STG.CLI_NOME), 1, DECODE(INSTR(TRIM(STG.CLI_NOME), ' '), 0, LENGTH(TRIM(STG.CLI_NOME)), INSTR(TRIM(STG.CLI_NOME), ' ')))
		END, 													-- 10 FIRSTNAM
		NULL,													-- 11 MIDNAM
		CASE
			WHEN STG.CLI_TIPOPESSOA = 2 THEN SUBSTR(TRIM(STG.CLI_CONTATO), INSTR(TRIM(STG.CLI_CONTATO), ' ') +1, DECODE(INSTR(TRIM(STG.CLI_CONTATO), ' '), 0, 0, LENGTH(TRIM(STG.CLI_CONTATO)) - INSTR(TRIM(STG.CLI_CONTATO), ' ')))
			ELSE                             SUBSTR(TRIM(STG.CLI_NOME), INSTR(TRIM(STG.CLI_NOME), ' ') +1, DECODE(INSTR(TRIM(STG.CLI_NOME), ' '), 0, 0, LENGTH(TRIM(STG.CLI_NOME)) - INSTR(TRIM(STG.CLI_NOME), ' ')))
		END, 													-- 12 LASTNAM
		' ', 													-- 13 SAL
		CASE 
			WHEN stg.CLI_TIPOPESSOA =  2 THEN stg.CLI_NOME
			ELSE NULL     
		END,													-- 14 COMPNAM
		stg.CLI_CPF,											-- 15 CPFCNPJ
		Null,													-- 16 MUNAPP
		stg.CLI_CONTAB_INSC_ESTADUAL,							-- 17 STTAPP
		Null,													-- 18 SEGACT
		CASE WHEN INSTR(NVL(STG.CLI_EMAIL,''),'@') < 1 THEN
		LOWER(STG.CLI_EMAIL||'@brturbo.com.br')
		ELSE
		LOWER(STG.CLI_EMAIL) end 
		AS CLI_EMAIL,											-- 19 EMAALT
		'A',													-- 20 CODACTSTEBRM
		'BRT-' || stg.CLI_COD,									-- 21 CODACTBRM
		stg.CLI_COD,											-- 22 CODACTBLL
		3,														-- 23 CODHOSTCRM
		3,														-- 24 CODHOSTBLL
		CASE 
         	WHEN UPPER(stg.CLI_NOME) = 'FULANO DE TAL'
              OR UPPER(stg.CLI_EMAIL) LIKE 'TESTEPRODUTO%'
              OR UPPER(stg.CLI_NOME) LIKE 'TESTEPRODUTO%'
              OR UPPER(stg.Cli_Login) LIKE 'TESTEPRODUTO%' THEN 1
         	ELSE 0
   	 	END,													-- 25 FLGTST
		to_date(stg.CLI_DATNAS,'DD/MM/YYYY'),					-- 26 BIRTHDAY_T
		NULL,													-- 27 BROADBAND_FLAG
		NULL,													-- 28 CHILDREN_COUNT
		DECODE(stg.CLI_SEXO,'F',1,'M',2,NULL),					-- 29 GENDER
		stg.CLI_MRSCODE,										-- 30 MARITAL_STATUS
		CASE WHEN stg.CLI_TIPOPESSOA = 2
			THEN stg.CLI_CONTATO
			ELSE NULL 
		END ,													-- 31 PJ_NAME
		NULL,													-- 32 PPZ_LOGIN
		stg.CLI_EDLCODE,										-- 33 SCHOLARITY
		NULL,													-- 34 SECRET_ANSWER	
		NULL, 													-- 35 SECRET_QUESTION
		'I',													-- 36 OPERACAO
		NULL													-- 37 CD_EXEC
		,SYSDATE AS INSDTE
        ,NULL AS UPDDTE
	FROM	
	APP_STGOWN.B_CRM_CLIENTE STG
	WHERE CLI_HDKORGCOD IN (SELECT CODETPLEG FROM APP_RELOWN.REL_BRAND_ENTERPRISE WHERE CODHOSTLEG=3);
	
	COMMIT;
	
EXEC DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'DD-MM-YYYY HH24:MI:SS')||'- TERMINO');

SPOOL OFF;

EXIT;
/